// AUTO-GENERATED MENU DATA FROM Mamak_Menu_Malaysia.docx
// DO NOT EDIT DIRECTLY

class MenuData {
  static const List<Map<String, dynamic>> items = [

    {
      'id': 'roti_kosong_roti_canai',
      'name': 'Roti Kosong (Roti Canai)',
      'price': 2.34,
      'imagePath': 'assets/roti_canai.png',
      'category': 'Roti / Flatbreads',
      'tags': ['SPICY'],
      'description': "Plain flaky flatbread, served with dhal curry & sambal",
      'calories': '350 Kcal',
    },
    {
      'id': 'roti_telur',
      'name': 'Roti Telur',
      'price': 3.9,
      'imagePath': 'assets/roti_telur.png',
      'category': 'Roti / Flatbreads',
      'tags': ['WITH EGG'],
      'description': "Roti canai with egg inside",
      'calories': '350 Kcal',
    },
    {
      'id': 'roti_susu',
      'name': 'Roti Susu',
      'price': 3.64,
      'imagePath': 'assets/roti_susu.png',
      'category': 'Roti / Flatbreads',
      'tags': ['SWEET'],
      'description': "Roti with condensed milk",
      'calories': '350 Kcal',
    },
    {
      'id': 'roti_tampal',
      'name': 'Roti Tampal',
      'price': 3.9,
      'imagePath': 'assets/roti_tampal.png',
      'category': 'Roti / Flatbreads',
      'tags': ['WITH EGG'],
      'description': "Roti with fried egg \"pasted\" on top",
      'calories': '350 Kcal',
    },
    {
      'id': 'roti_boom',
      'name': 'Roti Boom',
      'price': 7.15,
      'imagePath': 'assets/roti_boom.png',
      'category': 'Roti / Flatbreads',
      'tags': ['WITH EGG'],
      'description': "Roti with egg & minced meat, folded square",
      'calories': '350 Kcal',
    },
    {
      'id': 'roti_cheese',
      'name': 'Roti Cheese',
      'price': 7.15,
      'imagePath': 'assets/roti_cheese.png',
      'category': 'Roti / Flatbreads',
      'tags': ['CHEESY'],
      'description': "Roti with melted cheese",
      'calories': '350 Kcal',
    },
    {
      'id': 'roti_sardin',
      'name': 'Roti Sardin',
      'price': 9.1,
      'imagePath': 'assets/roti_sardin.png',
      'category': 'Roti / Flatbreads',
      'tags': ['LOCAL FAVORITE'],
      'description': "Roti stuffed with sardine filling",
      'calories': '350 Kcal',
    },
    {
      'id': 'roti_tisu',
      'name': 'Roti Tisu',
      'price': 4.0,
      'imagePath': 'assets/roti_tisu.png',
      'category': 'Roti / Flatbreads',
      'tags': ['SWEET'],
      'description': "Paper-thin crispy cone drizzled with condensed milk",
      'calories': '350 Kcal',
    },
    {
      'id': 'roti_bakar',
      'name': 'Roti Bakar',
      'price': 3.0,
      'imagePath': 'assets/roti_bakar.png',
      'category': 'Roti / Flatbreads',
      'tags': ['LOCAL FAVORITE'],
      'description': "Toasted bread with kaya (coconut jam) & butter",
      'calories': '350 Kcal',
    },
    {
      'id': 'nasi_goreng_ayam',
      'name': 'Nasi Goreng Ayam',
      'price': 9.75,
      'imagePath': 'assets/nasi_goreng_ayam.png',
      'category': 'Nasi Goreng / Fried Rice',
      'tags': ['LOCAL FAVORITE'],
      'description': "Fried rice with chicken",
      'calories': '750 Kcal',
    },
    {
      'id': 'nasi_goreng_daging',
      'name': 'Nasi Goreng Daging',
      'price': 10.4,
      'imagePath': 'assets/nasi_goreng_daging.png',
      'category': 'Nasi Goreng / Fried Rice',
      'tags': ['LOCAL FAVORITE'],
      'description': "Fried rice with beef",
      'calories': '750 Kcal',
    },
    {
      'id': 'nasi_goreng_ayam_pattaya',
      'name': 'Nasi Goreng Ayam Pattaya',
      'price': 11.05,
      'imagePath': 'assets/nasi_goreng_pattaya.png',
      'category': 'Nasi Goreng / Fried Rice',
      'tags': ['WITH EGG'],
      'description': "Chicken fried rice wrapped in egg omelette",
      'calories': '750 Kcal',
    },
    {
      'id': 'nasi_goreng_kampung',
      'name': 'Nasi Goreng Kampung',
      'price': 11.7,
      'imagePath': 'assets/nasi_goreng_kampung.png',
      'category': 'Nasi Goreng / Fried Rice',
      'tags': ['WITH EGG'],
      'description': "Village-style fried rice with anchovies, kangkung & egg",
      'calories': '750 Kcal',
    },
    {
      'id': 'nasi_goreng_seafood',
      'name': 'Nasi Goreng Seafood',
      'price': 12.35,
      'imagePath': 'assets/nasi_goreng_seafood.png',
      'category': 'Nasi Goreng / Fried Rice',
      'tags': ['LOCAL FAVORITE'],
      'description': "Fried rice with shrimp, squid & fish",
      'calories': '750 Kcal',
    },
    {
      'id': 'nasi_goreng_paprik_daging',
      'name': 'Nasi Goreng Paprik Daging',
      'price': 14.3,
      'imagePath': 'assets/nasi_goreng_paprik_daging.png',
      'category': 'Nasi Goreng / Fried Rice',
      'tags': ['SPICY'],
      'description': "Stir-fried rice with beef in spicy paprik sauce",
      'calories': '750 Kcal',
    },
    {
      'id': 'nasi_goreng_ayam_goreng',
      'name': 'Nasi Goreng Ayam Goreng',
      'price': 14.3,
      'imagePath': 'assets/nasi_goreng_ayam_goreng.png',
      'category': 'Nasi Goreng / Fried Rice',
      'tags': ['LOCAL FAVORITE'],
      'description': "Fried rice with a side of crispy fried chicken",
      'calories': '750 Kcal',
    },
    {
      'id': 'nasi_goreng_special',
      'name': 'Nasi Goreng Special',
      'price': 16.9,
      'imagePath': 'assets/nasi_goreng_special.png',
      'category': 'Nasi Goreng / Fried Rice',
      'tags': ['WITH EGG'],
      'description': "Ultimate fried rice with everything – chicken, beef, seafood, egg",
      'calories': '750 Kcal',
    },
    {
      'id': 'maggi_goreng',
      'name': 'Maggi Goreng',
      'price': 5.0,
      'imagePath': 'assets/mee_goreng.png',
      'category': 'Mee / Noodles',
      'tags': ['SPICY', 'WITH EGG'],
      'description': "Stir-fried instant noodles with veg, egg & sambal",
      'calories': '620 Kcal',
    },
    {
      'id': 'mee_goreng_ayam',
      'name': 'Mee Goreng Ayam',
      'price': 9.75,
      'imagePath': 'assets/mee_goreng_ayam.png',
      'category': 'Mee / Noodles',
      'tags': ['LOCAL FAVORITE'],
      'description': "Fried noodles with chicken",
      'calories': '620 Kcal',
    },
    {
      'id': 'mee_goreng_mamak_ayam',
      'name': 'Mee Goreng Mamak Ayam',
      'price': 11.05,
      'imagePath': 'assets/mee_goreng.png',
      'category': 'Mee / Noodles',
      'tags': ['LOCAL FAVORITE'],
      'description': "Mamak-style fried noodles with chicken",
      'calories': '620 Kcal',
    },
    {
      'id': 'nasi_lemak_biasa',
      'name': 'Nasi Lemak Biasa',
      'price': 4.0,
      'imagePath': 'assets/nasi_lemak.png',
      'category': 'Nasi Dishes',
      'tags': ['SPICY', 'WITH EGG'],
      'description': "Coconut rice with sambal, egg, peanuts & anchovies",
      'calories': '750 Kcal',
    },
    {
      'id': 'nasi_kandar_with_side',
      'name': 'Nasi Kandar (with side)',
      'price': 7.0,
      'imagePath': 'assets/nasi_kandar.png',
      'category': 'Nasi Dishes',
      'tags': ['LOCAL FAVORITE'],
      'description': "Steamed rice with mixed curries & your choice of protein",
      'calories': '750 Kcal',
    },
    {
      'id': 'nasi_briyani_ayam_daging',
      'name': 'Nasi Briyani Ayam/Daging',
      'price': 12.0,
      'imagePath': 'assets/nasi_briyani_ayam_daging.png',
      'category': 'Nasi Dishes',
      'tags': ['LOCAL FAVORITE'],
      'description': "Fragrant briyani rice with chicken or beef",
      'calories': '750 Kcal',
    },
    {
      'id': 'ayam_goreng',
      'name': 'Ayam Goreng',
      'price': 6.5,
      'imagePath': 'assets/ayam_goreng.png',
      'category': 'Lauk / Sides',
      'tags': ['LOCAL FAVORITE'],
      'description': "Crispy spiced fried chicken",
      'calories': '300 Kcal',
    },
    {
      'id': 'kari_ayam',
      'name': 'Kari Ayam',
      'price': 6.5,
      'imagePath': 'assets/kari_ayam.png',
      'category': 'Lauk / Sides',
      'tags': ['SPICY'],
      'description': "Chicken curry",
      'calories': '300 Kcal',
    },
    {
      'id': 'ayam_masak_kicap',
      'name': 'Ayam Masak Kicap',
      'price': 6.5,
      'imagePath': 'assets/ayam_masak_kicap.png',
      'category': 'Lauk / Sides',
      'tags': ['LOCAL FAVORITE'],
      'description': "Soy-braised chicken",
      'calories': '300 Kcal',
    },
    {
      'id': 'tandoori_chicken',
      'name': 'Tandoori Chicken',
      'price': 7.0,
      'imagePath': 'assets/tandoori_chicken.png',
      'category': 'Lauk / Sides',
      'tags': ['LOCAL FAVORITE'],
      'description': "Clay-oven roasted spiced chicken",
      'calories': '300 Kcal',
    },
    {
      'id': 'thosai',
      'name': 'Thosai',
      'price': 2.5,
      'imagePath': 'assets/thosai.png',
      'category': 'Other / Snacks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Fermented rice & lentil crepe, served with chutneys & dhal",
      'calories': '300 Kcal',
    },
    {
      'id': 'chapati',
      'name': 'Chapati',
      'price': 3.0,
      'imagePath': 'assets/chapati.png',
      'category': 'Other / Snacks',
      'tags': ['SPICY'],
      'description': "Whole wheat flatbread with dhal or curry",
      'calories': '300 Kcal',
    },
    {
      'id': 'murtabak_ayam_daging',
      'name': 'Murtabak Ayam/Daging',
      'price': 6.0,
      'imagePath': 'assets/murtabak.png',
      'category': 'Other / Snacks',
      'tags': ['WITH EGG'],
      'description': "Stuffed pan-fried bread with spiced chicken or beef & egg",
      'calories': '300 Kcal',
    },
    {
      'id': 'cendol',
      'name': 'Cendol',
      'price': 3.0,
      'imagePath': 'assets/cendol.png',
      'category': 'Other / Snacks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Iced dessert with coconut milk, green jelly & gula melaka",
      'calories': '300 Kcal',
    },
    {
      'id': 'abc_ais_batu_campur',
      'name': 'ABC (Ais Batu Campur)',
      'price': 4.5,
      'imagePath': 'assets/abc_ais_batu_campur.png',
      'category': 'Other / Snacks',
      'tags': ['SWEET'],
      'description': "Shaved ice with red beans, corn, jelly, syrup & condensed milk",
      'calories': '300 Kcal',
    },
    {
      'id': 'roti_pisang',
      'name': 'Roti Pisang',
      'price': 4.5,
      'imagePath': 'assets/roti_pisang.png',
      'category': 'Other / Snacks',
      'tags': ['SWEET'],
      'description': "Roti with sliced bananas & condensed milk",
      'calories': '300 Kcal',
    },
    {
      'id': 'teh_o',
      'name': 'Teh O',
      'price': 1.95,
      'imagePath': 'assets/teh_o.png',
      'category': 'Hot Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Plain black tea (no milk)",
      'calories': '220 Kcal',
    },
    {
      'id': 'kopi_o',
      'name': 'Kopi O',
      'price': 1.95,
      'imagePath': 'assets/kopi_o.png',
      'category': 'Hot Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Black coffee (no milk)",
      'calories': '220 Kcal',
    },
    {
      'id': 'teh_tarik',
      'name': 'Teh Tarik',
      'price': 3.25,
      'imagePath': 'assets/teh_tarik.png',
      'category': 'Hot Drinks',
      'tags': ['SWEET'],
      'description': "Pulled milk tea — sweet & frothy",
      'calories': '220 Kcal',
    },
    {
      'id': 'teh_susu',
      'name': 'Teh Susu',
      'price': 3.25,
      'imagePath': 'assets/teh_susu.png',
      'category': 'Hot Drinks',
      'tags': ['SWEET'],
      'description': "Tea with condensed milk",
      'calories': '220 Kcal',
    },
    {
      'id': 'teh_c',
      'name': 'Teh C',
      'price': 3.25,
      'imagePath': 'assets/teh_c.png',
      'category': 'Hot Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Tea with evaporated milk",
      'calories': '220 Kcal',
    },
    {
      'id': 'kopi_susu',
      'name': 'Kopi Susu',
      'price': 3.9,
      'imagePath': 'assets/kopi_susu.png',
      'category': 'Hot Drinks',
      'tags': ['SWEET'],
      'description': "Coffee with condensed milk",
      'calories': '220 Kcal',
    },
    {
      'id': 'kopi_c',
      'name': 'Kopi C',
      'price': 3.25,
      'imagePath': 'assets/kopi_c.png',
      'category': 'Hot Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Coffee with evaporated milk",
      'calories': '220 Kcal',
    },
    {
      'id': 'kopi_tarik',
      'name': 'Kopi Tarik',
      'price': 3.25,
      'imagePath': 'assets/kopi_tarik.png',
      'category': 'Hot Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Pulled white coffee",
      'calories': '220 Kcal',
    },
    {
      'id': 'teh_o_ais',
      'name': 'Teh O Ais',
      'price': 2.2,
      'imagePath': 'assets/teh_o_ais.png',
      'category': 'Cold Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Iced plain tea",
      'calories': '220 Kcal',
    },
    {
      'id': 'kopi_o_ais',
      'name': 'Kopi O Ais',
      'price': 2.2,
      'imagePath': 'assets/kopi_o_ais.png',
      'category': 'Cold Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Iced black coffee",
      'calories': '220 Kcal',
    },
    {
      'id': 'teh_ais',
      'name': 'Teh Ais',
      'price': 3.25,
      'imagePath': 'assets/teh_ais.png',
      'category': 'Cold Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Iced milk tea",
      'calories': '220 Kcal',
    },
    {
      'id': 'kopi_ais',
      'name': 'Kopi Ais',
      'price': 3.25,
      'imagePath': 'assets/kopi_ais.png',
      'category': 'Cold Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Iced white coffee",
      'calories': '220 Kcal',
    },
    {
      'id': 'milo_ais',
      'name': 'Milo Ais',
      'price': 3.5,
      'imagePath': 'assets/milo_ais.png',
      'category': 'Cold Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Iced chocolate malt drink (the classic!)",
      'calories': '220 Kcal',
    },
    {
      'id': 'sirap_bandung',
      'name': 'Sirap Bandung',
      'price': 3.0,
      'imagePath': 'assets/sirap_bandung.png',
      'category': 'Cold Drinks',
      'tags': ['LOCAL FAVORITE'],
      'description': "Rose syrup with evaporated milk",
      'calories': '220 Kcal',
    },
  ];
}
